# Map data
maps:
    map1:
        name: A
        mapref: 1
    map2:
        name: B
        mapref: 2
    map3:
        name: C
        mapref: 3
    map4:
        name: D
        mapref: 4
    map5:
        name: E
        mapref: 5